USE [master]
GO
/****** Object:  Database [BLUEBANK]    Script Date: 01/11/2020 17:12:00 ******/
CREATE DATABASE [BLUEBANK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bluebankdb', FILENAME = N'D:\Repos\DncBlueBank\DncBlueBank\App_Data\bluebankdb.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bluebankdb_log', FILENAME = N'D:\Repos\DncBlueBank\DncBlueBank\App_Data\bluebankdb_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [BLUEBANK] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BLUEBANK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BLUEBANK] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BLUEBANK] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BLUEBANK] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BLUEBANK] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BLUEBANK] SET ARITHABORT OFF 
GO
ALTER DATABASE [BLUEBANK] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BLUEBANK] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [BLUEBANK] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BLUEBANK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BLUEBANK] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BLUEBANK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BLUEBANK] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BLUEBANK] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BLUEBANK] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BLUEBANK] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BLUEBANK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BLUEBANK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BLUEBANK] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BLUEBANK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BLUEBANK] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BLUEBANK] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BLUEBANK] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BLUEBANK] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BLUEBANK] SET  MULTI_USER 
GO
ALTER DATABASE [BLUEBANK] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BLUEBANK] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BLUEBANK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BLUEBANK] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BLUEBANK] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BLUEBANK] SET QUERY_STORE = OFF
GO
USE [BLUEBANK]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [BLUEBANK]
GO
/****** Object:  User [IRONSIDE\diego]    Script Date: 01/11/2020 17:12:00 ******/
CREATE USER [IRONSIDE\diego] FOR LOGIN [IRONSIDE\diego] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [IRONSIDE\diego]
GO
/****** Object:  Table [dbo].[Accounts]    Script Date: 01/11/2020 17:12:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Agency] [varchar](10) NOT NULL,
	[Number] [varchar](10) NOT NULL,
	[Balance] [money] NOT NULL,
	[Owner] [varchar](60) NOT NULL,
 CONSTRAINT [PK__tmp_ms_x__3214EC07E56ECB57] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 01/11/2020 17:12:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AccountID] [int] NOT NULL,
	[Type] [tinyint] NOT NULL,
	[Value] [money] NOT NULL,
	[DateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Accounts] ADD  CONSTRAINT [DF__tmp_ms_xx__Saldo__1367E606]  DEFAULT ((0)) FOR [Balance]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_AccountsFrom] FOREIGN KEY([AccountID])
REFERENCES [dbo].[Accounts] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_AccountsFrom]
GO
USE [master]
GO
ALTER DATABASE [BLUEBANK] SET  READ_WRITE 
GO
